version: "3.7"
services:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "mi-banco"

  server:
    build: ./server
    image: seventrust/mean_backend
    ports:
      - "8000:8000"
    links:
      - mongo-db

  client:
    build: ./client
    image: seventrust/mean_frontend
    ports:
      - "80:80"
